{
 "title": "Application Logs Dashboard",
 "tags": [
  "loki",
  "logs"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "level", "query": "INFO,ERROR,WARNING,CRITICAL" }
  ]
 },
 "panels": [
  {
   "title": "Log Rate by Level",
   "type": "timeseries",
   "description": "Log line rate over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(level) (rate({service=\"demo-python-app\"} | pattern `<_> - <_> - <level> - <message>` | level != `` [5m]))"
    }
   ]
  },
  {
   "title": "Error Count (5m)",
   "type": "stat",
   "description": "Counts of error logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({service=\"demo-python-app\"} |= `error` [5m])"
    }
   ]
  },
  {
   "title": "Application Logs by Level",
   "type": "logs",
   "description": "Filter logs by log level",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{service=\"demo-python-app\"} | pattern `<_> - <_> - <level> - <message>` | level = \"${level:raw}\""
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "description": "Error logs with context",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{service=\"demo-python-app\"} |= `error`"
    }
   ]
  }
 ]
}